import pygame

ANCHO_VENTANA = 1500
ALTO_VENTANA = 800
GROUND_LEVEL = 600
FPS = 60


EXPAND_TIME = 2000
DIRECTION_L = 0
DIRECTION_R = 1
GROUND_COLLIDE_H = 8 # Aprox Gravedad/2 + 1
DEBUG = False

# COLOR CONSTANTS
C_RED = (255,0,0)
C_GREEN = (0,255,0)
C_BLUE = (0,0,255)
C_BLACK = (0,0,0)
C_WHITE = (255,255,255)
C_PINK = (255, 0, 160)
C_PEACH = (255, 118, 95)
C_BLUE_2 = (38, 0, 160)
C_YELLOW_2 = (255, 174, 0)
C_GREEEN_2 = (38, 137, 0)
C_ORANGE = (255, 81, 0)
C_VICTORY =  (255, 215, 0)

# MOUSE CONSTANTS
M_STATE_NORMAL = 0
M_STATE_HOVER = 1
M_STATE_CLICK = 3
M_BRIGHT_HOVER = (32,32,32)
M_BRIGHT_CLICK = (32,32,32)

# IMAGE CONSTANTS
SINGLEPLAYER_VICTORY_IMAGE_PATH = "images/assets/victory-pole_L.png"
MULTIPLAYER_VICTORY_IMAGE_PATH = "images/assets/victory-pole.png"
PATH_USER_BULLET = "images/assets/bullet_3.png"
PATH_COWBOY_IMAGES = "images/caracters/players/cowboy"
PATH_COWGIRL_IMAGES = "images/caracters/players/cowgirl"

# GAME CONSTANTS
NAME_FORM_MENU_B = "form_menu_B"

# PLAYER CONSTANTS
LEFT = "left"
RIGHT = "right"
JUMP = "jump"
ATTACK = "attack"
SHOOT = "shoot"

PLAYER_1_LEFT = pygame.K_LEFT
PLAYER_1_RIGHT = pygame.K_RIGHT
PLAYER_1_JUMP = pygame.K_UP
PLAYER_1_ATTACK = pygame.K_KP1
PLAYER_1_SHOOT = pygame.K_KP2
PLAYER_1_KEYS = {LEFT: PLAYER_1_LEFT, RIGHT: PLAYER_1_RIGHT, JUMP: PLAYER_1_JUMP, ATTACK: PLAYER_1_ATTACK, SHOOT: PLAYER_1_SHOOT}

PLAYER_2_LEFT = pygame.K_a
PLAYER_2_RIGHT = pygame.K_d
PLAYER_2_JUMP = pygame.K_SPACE
PLAYER_2_ATTACK = pygame.K_g
PLAYER_2_SHOOT = pygame.K_h

PLAYER_2_KEYS = {LEFT: PLAYER_2_LEFT, RIGHT: PLAYER_2_RIGHT, JUMP: PLAYER_2_JUMP, ATTACK: PLAYER_2_ATTACK, SHOOT: PLAYER_2_SHOOT}

PLAYER_SHOOT_INTERVAL = 400
ENEMY_ATTACK_INTERVAL = 400

# LEVEL_CONSTANTS
LEVEL_1 = "L1"