import pygame

ANCHO_VENTANA = 1500
ALTO_VENTANA = 843
GROUND_LEVEL = 775
FPS = 60


EXPAND_TIME = 2000
DIRECTION_L = 0
DIRECTION_R = 1
GROUND_COLLIDE_H = 15 # Aprox Gravedad/2 + 1
DEBUG = False
DATABASE_NAME = "OrcoCalipsis.db"
GAME_TITLE = "OrcoCalipsis"
BOSS_DAMAGE = 50

# COLOR CONSTANTS
C_RED = (255,0,0)
C_GREEN = (0,255,0)
C_BLUE = (0,0,255)
C_BLACK = (0,0,0)
C_WHITE = (255,255,255)
C_PINK = (255, 0, 160)
C_PEACH = (255, 118, 95)
C_BLUE_2 = (38, 0, 160)
C_YELLOW_2 = (255, 174, 0)
C_GREEEN_2 = (38, 137, 0)
C_ORANGE = (255, 81, 0)
C_VICTORY =  (255, 215, 0)
C_BLOOD = (230, 37, 72, 0.7)
C_FALL =  (139, 69, 19)

# MOUSE CONSTANTS
M_STATE_NORMAL = 0
M_STATE_HOVER = 1
M_STATE_CLICK = 3
M_BRIGHT_HOVER = (32,32,32)
M_BRIGHT_CLICK = (32,32,32)

# IMAGE CONSTANTS
SINGLEPLAYER_VICTORY_IMAGE_PATH = "images/assets/victory-pole_L.png"
MULTIPLAYER_VICTORY_IMAGE_PATH = "images/assets/victory-pole.png"
PATH_USER_BULLET = "images/assets/bullet_3.png"
PATH_COWBOY_IMAGES = "images/caracters/players/cowboy"
PATH_COWGIRL_IMAGES = "images/caracters/players/cowgirl"
PLAYER_ICON_PATH = "images/assets/player_icon.png"
LEVEL_1_BACKGROUND = "images/locations/set_bg_03/01/game_background_1.png"
LEVEL_2_BACKGROUND = "images/locations/set_bg_03/03/game_background_3.1.png"
LEVEL_3_BACKGROUND = "images/locations/set_bg_05/3_game_background/3_game_background.png"
FOOD_IMG_DIR = "images/assets/consumables/food"
LEVEL_2_BOSS_IMG = "images/caracters/enemies/bosses/ork_axe"
LEVEL_3_BOSS_IMG = "images/caracters/enemies/bosses/troll_stone_hammer"
START_IMAGE_PATH = "images/gui/start-image/start_image.png"
BLOOD_FONT_PATH = "images/assets/fonts/ConflictDripsPersonalUseBold-WyKXn.ttf"
MUSIC_PATH = "images/assets/music/Platformer Underground Level Game Music - Royalty Free Music.mp3"
PLATFORM_HEIGHT = 25
PLATFORM_WIDTH = 25

# GAME CONSTANTS
NAME_FORM_MENU_B = "form_menu_B"
START_MENU_NAME = "START_MENU"
SETTINGS_MENU_NAME = "SETTINGS"
RANKINGS_MENU_NAME = "RANKINGS"
YOU_WIN_FORM_NAME = "YOU_WIN"
PARTICLE_AMOUNT = 20
GRAVITY_SPEED = 5
TERMINAL_VELOCITY = 40
MENU_FORM_WIDTH = 800
MENU_FORM_HEIGHT = 650
BULLET_DAMAGE = 5
ENEMY_DAMAGE = 25

# PLAYER CONSTANTS
LEFT = "left"
RIGHT = "right"
JUMP = "jump"
ATTACK = "attack"
USE = "use"
SHOOT = "shoot"

PLAYER_1_LEFT = pygame.K_a
PLAYER_1_RIGHT = pygame.K_d
PLAYER_1_JUMP = pygame.K_SPACE
PLAYER_1_ATTACK = pygame.K_g
PLAYER_1_SHOOT = pygame.K_h
PLAYER_1_USE = pygame.K_e

PLAYER_2_LEFT = pygame.K_LEFT
PLAYER_2_RIGHT = pygame.K_RIGHT
PLAYER_2_JUMP = pygame.K_UP
PLAYER_2_ATTACK = pygame.K_KP1
PLAYER_2_SHOOT = pygame.K_KP2
PLAYER_2_USE = pygame.K_KP3

PLAYER_1_KEYS = {LEFT: PLAYER_1_LEFT, RIGHT: PLAYER_1_RIGHT, JUMP: PLAYER_1_JUMP, ATTACK: PLAYER_1_ATTACK, SHOOT: PLAYER_1_SHOOT, USE: PLAYER_1_USE}

PLAYER_2_KEYS = {LEFT: PLAYER_2_LEFT, RIGHT: PLAYER_2_RIGHT, JUMP: PLAYER_2_JUMP, ATTACK: PLAYER_2_ATTACK, SHOOT: PLAYER_2_SHOOT, USE: PLAYER_2_USE}

PLAYER_SHOOT_INTERVAL = 400
ENEMY_ATTACK_INTERVAL = 400
BOSS_ATTACK_INTERVAL = 1000

# LEVEL_CONSTANTS
LEVEL_1 = "L1"
LEVEL_2 = "L2"
LEVEL_3 = "L3"

LEFT_PLATFORM_TYPE = 12
CENTER_PLATFORM_TYPE = 13
RIGHT_PLATFORM_TYPE = 14

# FILE CONSTANTS
JSON_PLATFORMS_KEY = "platforms"
JSON_PLATFORM_X_KEY = "start_x"
JSON_PLATFORM_Y_KEY = "start_y"
JSON_PLATFORM_DISTANCE_X_KEY = "distance_x"
JSON_PLATFORM_DISTANCE_Y_KEY = "distance_y"
JSON_PLATFORM_INNER_AMOUNT_KEY = "inner_block_amount"
JSON_PLATFORM_TEXTURE_TYPE_KEY = "texture_type"
JSON_PLATFORM_SPEED_KEY = "speed"